SELECT tt.*,
    up.payment_total,
    up.register_date_kiev `date_reg`
from (
        SELECT m.date_created_kiev `date`,
            m.time_created_kiev `time`,
            m.recipient_external_id `man_external_id`,
            m.recipient_id `man_id`,
            m.sender_external_id `woman_external_id`,
            m.sender_id `woman_id`,
            m.message_content,
            uo.username,
            uo.firstname,
            case
                when uo.agency_id = 13
                or uo.agency_id = 650 then 'Isida'
                when uo.agency_id = 12 then 'HighFly'
                when uo.agency_id = 425 then 'School'
                ELSE 'other'
            END AS `agency`,
            case
                when m.message_content LIKE "% moan %" then "moan"
                when m.message_content LIKE "% take it in my mouth %" then "take it in my mouth"
                when m.message_content LIKE "% breaks and nipples %" then "breaks and nipples"
                when m.message_content LIKE "% suck me dry %" then "suck me dry"
                when m.message_content LIKE "% sucking licking %" then "sucking licking"
                when m.message_content LIKE "% to kiss the sweetest places on my body %" then "to kiss the sweetest places on my body"
                when m.message_content LIKE "% CYKA %" then "CYKA"
                when m.message_content LIKE "% intimate %" then "intimate"
                when m.message_content LIKE "% groin %" then "groin"
                when m.message_content LIKE "% masturbator %" then "masturbator"
                when m.message_content LIKE "% arouse %" then "arouse"
                when m.message_content LIKE "% dogs out %" then "dogs out"
                when m.message_content LIKE "% squirt %" then "squirt"
                when m.message_content LIKE "% oral %" then "oral"
                when m.message_content LIKE "% erect breasts %" then "erect breasts"
                when m.message_content LIKE "% curvy bottom %" then "curvy bottom"
                when m.message_content LIKE "% fuk off %" then "fuk off"
                when m.message_content LIKE "% deepthroating %" then "deepthroating"
                when m.message_content LIKE "% lusty chat %" then "lusty chat"
                when m.message_content LIKE "% naughty pic %" then "naughty pic"
                when m.message_content LIKE "% lace lingerie set %" then "lace lingerie set"
                when m.message_content LIKE "% without clothe %" then "without clothe"
                when m.message_content LIKE "% main organ %" then "main organ"
                when m.message_content LIKE "% collection of gadgets for single ladies %" then "collection of gadgets for single ladies"
                when m.message_content LIKE "% hottass %" then "hottass"
                when m.message_content LIKE "% striptease %" then "striptease"
                when m.message_content LIKE "% dominate %" then "dominate"
                when m.message_content LIKE "% lick %" then "lick"
                when m.message_content LIKE "% legs are spread %" then "legs are spread"
                when m.message_content LIKE "% without pant %" then "without pant"
                when m.message_content LIKE "% turn you on %" then "turn you on"
                when m.message_content LIKE "% squeeze %" then "squeeze"
                when m.message_content LIKE "% vozbuzhdayesh %" then "vozbuzhdayesh"
                when m.message_content LIKE "% crotch up %" then "crotch up"
                when m.message_content LIKE "% genital %" then "genital"
                when m.message_content LIKE "% kum %" then "kum"
                when m.message_content LIKE "% wit woo %" then "wit woo"
                when m.message_content LIKE "% naked %" then "naked"
                when m.message_content LIKE "% puss  %" then "puss "
                when m.message_content LIKE "% You can sit on my face %" then "You can sit on my face"
                when m.message_content LIKE "% fuck with me %" then "fuck with me"
                when m.message_content LIKE "% teats %" then "teats"
                when m.message_content LIKE "% i wanna eat you %" then "i wanna eat you"
                when m.message_content LIKE "% please send me pic %" then "please send me pic"
                when m.message_content LIKE "% dic-photo %" then "dic-photo"
                when m.message_content LIKE "% dic pic %" then "dic pic"
                when m.message_content LIKE "% sexting %" then "sexting"
                when m.message_content LIKE "% throbbing %" then "throbbing"
                when m.message_content LIKE "% licker %" then "licker"
                when m.message_content LIKE "% cocksucker %" then "cocksucker"
                when m.message_content LIKE "% still keeping it straight %" then "still keeping it straight"
                when m.message_content LIKE "% dirty chat %" then "dirty chat"
                when m.message_content LIKE "% sexie %" then "sexie"
                when m.message_content LIKE "% intens and nakke %" then "intens and nakke"
                when m.message_content LIKE "% come off %" then "come off"
                when m.message_content LIKE "% saliva %" then "saliva"
                when m.message_content LIKE "% lube %" then "lube"
                when m.message_content LIKE "% coochie %" then "coochie"
                when m.message_content LIKE "% cowgirl %" then "cowgirl"
                when m.message_content LIKE "% doggy %" then "doggy"
                when m.message_content LIKE "% no clothing %" then "no clothing"
                when m.message_content LIKE "% eating pussy %" then "eating pussy"
                when m.message_content LIKE "% mistress %" then "mistress"
                when m.message_content LIKE "% bare %" then "bare"
                when m.message_content LIKE "% underwear %" then "underwear"
                when m.message_content LIKE "% hot night %" then "hot night"
                when m.message_content LIKE "% breasts %" then "breasts"
                when m.message_content LIKE "% hot lover %" then "hot lover"
                when m.message_content LIKE "% conjugal duty %" then "conjugal duty"
                when m.message_content LIKE "% throb %" then "throb"
                when m.message_content LIKE "% spank %" then "spank"
                when m.message_content LIKE "% setting on my face %" then "setting on my face"
                when m.message_content LIKE "% lingerie %" then "lingerie"
                when m.message_content LIKE "% sex pod %" then "sex pod"
                when m.message_content LIKE "% ecstasy %" then "ecstasy"
                when m.message_content LIKE "% condom %" then "condom"
                when m.message_content LIKE "% Contex %" then "Contex"
                when m.message_content LIKE "% Durex %" then "Durex"
                when m.message_content LIKE "% nightie %" then "nightie"
                when m.message_content LIKE "% betweenness %" then "betweenness"
                when m.message_content LIKE "% tie my hands %" then "tie my hands"
                when m.message_content LIKE "% kamasutra %" then "kamasutra"
                when m.message_content LIKE "% caresses %" then "caresses"
                when m.message_content LIKE "% bra %" then "bra"
                when m.message_content LIKE "% hose you down %" then "hose you down"
                when m.message_content LIKE "% 2g1c %" then "2g1c"
                when m.message_content LIKE "% 2 girls 1 cup %" then "2 girls 1 cup"
                when m.message_content LIKE "% acrotomophilia %" then "acrotomophilia"
                when m.message_content LIKE "% alabama hot pocket %" then "alabama hot pocket"
                when m.message_content LIKE "% alaskan pipeline %" then "alaskan pipeline"
                when m.message_content LIKE "% anal %" then "anal"
                when m.message_content LIKE "% anilingus %" then "anilingus"
                when m.message_content LIKE "% anus %" then "anus"
                when m.message_content LIKE "% apeshit %" then "apeshit"
                when m.message_content LIKE "% arsehole %" then "arsehole"
                when m.message_content LIKE "% ass %" then "ass"
                when m.message_content LIKE "% asshole %" then "asshole"
                when m.message_content LIKE "% assmunch %" then "assmunch"
                when m.message_content LIKE "% auto erotic %" then "auto erotic"
                when m.message_content LIKE "% autoerotic %" then "autoerotic"
                when m.message_content LIKE "% babeland %" then "babeland"
                when m.message_content LIKE "% baby batter %" then "baby batter"
                when m.message_content LIKE "% baby juice %" then "baby juice"
                when m.message_content LIKE "% ball gag %" then "ball gag"
                when m.message_content LIKE "% ball gravy %" then "ball gravy"
                when m.message_content LIKE "% ball kicking %" then "ball kicking"
                when m.message_content LIKE "% ball licking %" then "ball licking"
                when m.message_content LIKE "% ball sack %" then "ball sack"
                when m.message_content LIKE "% ball sucking %" then "ball sucking"
                when m.message_content LIKE "% bangbros %" then "bangbros"
                when m.message_content LIKE "% bangbus %" then "bangbus"
                when m.message_content LIKE "% bareback %" then "bareback"
                when m.message_content LIKE "% barely legal %" then "barely legal"
                when m.message_content LIKE "% barenaked %" then "barenaked"
                when m.message_content LIKE "% bastard %" then "bastard"
                when m.message_content LIKE "% bastardo %" then "bastardo"
                when m.message_content LIKE "% bastinado %" then "bastinado"
                when m.message_content LIKE "% bbw %" then "bbw"
                when m.message_content LIKE "% bdsm %" then "bdsm"
                when m.message_content LIKE "% beaner %" then "beaner"
                when m.message_content LIKE "% beaners %" then "beaners"
                when m.message_content LIKE "% beaver cleaver %" then "beaver cleaver"
                when m.message_content LIKE "% beaver lips %" then "beaver lips"
                when m.message_content LIKE "% beastiality %" then "beastiality"
                when m.message_content LIKE "% bestiality %" then "bestiality"
                when m.message_content LIKE "% big black %" then "big black"
                when m.message_content LIKE "% big breasts %" then "big breasts"
                when m.message_content LIKE "% big knockers %" then "big knockers"
                when m.message_content LIKE "% big tits %" then "big tits"
                when m.message_content LIKE "% bimbos %" then "bimbos"
                when m.message_content LIKE "% birdlock %" then "birdlock"
                when m.message_content LIKE "% bitch %" then "bitch"
                when m.message_content LIKE "% bitches %" then "bitches"
                when m.message_content LIKE "% black cock %" then "black cock"
                when m.message_content LIKE "% blonde action %" then "blonde action"
                when m.message_content LIKE "% blonde on blonde action %" then "blonde on blonde action"
                when m.message_content LIKE "% blowjob %" then "blowjob"
                when m.message_content LIKE "% blow job %" then "blow job"
                when m.message_content LIKE "% blow your load %" then "blow your load"
                when m.message_content LIKE "% blue waffle %" then "blue waffle"
                when m.message_content LIKE "% blumpkin %" then "blumpkin"
                when m.message_content LIKE "% bollocks %" then "bollocks"
                when m.message_content LIKE "% bondage %" then "bondage"
                when m.message_content LIKE "% boner %" then "boner"
                when m.message_content LIKE "% boob %" then "boob"
                when m.message_content LIKE "% boobs %" then "boobs"
                when m.message_content LIKE "% booty call %" then "booty call"
                when m.message_content LIKE "% brown showers %" then "brown showers"
                when m.message_content LIKE "% brunette action %" then "brunette action"
                when m.message_content LIKE "% bukkake %" then "bukkake"
                when m.message_content LIKE "% bulldyke %" then "bulldyke"
                when m.message_content LIKE "% bullet vibe %" then "bullet vibe"
                when m.message_content LIKE "% bullshit %" then "bullshit"
                when m.message_content LIKE "% bung hole %" then "bung hole"
                when m.message_content LIKE "% bunghole %" then "bunghole"
                when m.message_content LIKE "% busty %" then "busty"
                when m.message_content LIKE "% butt %" then "butt"
                when m.message_content LIKE "% buttcheeks %" then "buttcheeks"
                when m.message_content LIKE "% butthole %" then "butthole"
                when m.message_content LIKE "% camel toe %" then "camel toe"
                when m.message_content LIKE "% camgirl %" then "camgirl"
                when m.message_content LIKE "% camslut %" then "camslut"
                when m.message_content LIKE "% camwhore %" then "camwhore"
                when m.message_content LIKE "% carpet muncher %" then "carpet muncher"
                when m.message_content LIKE "% carpetmuncher %" then "carpetmuncher"
                when m.message_content LIKE "% chocolate rosebuds %" then "chocolate rosebuds"
                when m.message_content LIKE "% cialis %" then "cialis"
                when m.message_content LIKE "% circlejerk %" then "circlejerk"
                when m.message_content LIKE "% cleveland steamer %" then "cleveland steamer"
                when m.message_content LIKE "% clit %" then "clit"
                when m.message_content LIKE "% clitoris %" then "clitoris"
                when m.message_content LIKE "% clover clamps %" then "clover clamps"
                when m.message_content LIKE "% clusterfuck %" then "clusterfuck"
                when m.message_content LIKE "% cock %" then "cock"
                when m.message_content LIKE "% cocks %" then "cocks"
                when m.message_content LIKE "% coprolagnia %" then "coprolagnia"
                when m.message_content LIKE "% coprophilia %" then "coprophilia"
                when m.message_content LIKE "% cornhole %" then "cornhole"
                when m.message_content LIKE "% coon %" then "coon"
                when m.message_content LIKE "% coons %" then "coons"
                when m.message_content LIKE "% creampie %" then "creampie"
                when m.message_content LIKE "% cum %" then "cum"
                when m.message_content LIKE "% cumming %" then "cumming"
                when m.message_content LIKE "% cumshot %" then "cumshot"
                when m.message_content LIKE "% cumshots %" then "cumshots"
                when m.message_content LIKE "% cunnilingus %" then "cunnilingus"
                when m.message_content LIKE "% cunt %" then "cunt"
                when m.message_content LIKE "% darkie %" then "darkie"
                when m.message_content LIKE "% date rape %" then "date rape"
                when m.message_content LIKE "% daterape %" then "daterape"
                when m.message_content LIKE "% deep throat %" then "deep throat"
                when m.message_content LIKE "% deepthroat %" then "deepthroat"
                when m.message_content LIKE "% dendrophilia %" then "dendrophilia"
                when m.message_content LIKE "% dick %" then "dick"
                when m.message_content LIKE "% dildo %" then "dildo"
                when m.message_content LIKE "% dingleberry %" then "dingleberry"
                when m.message_content LIKE "% dingleberries %" then "dingleberries"
                when m.message_content LIKE "% dirty pillows %" then "dirty pillows"
                when m.message_content LIKE "% dirty sanchez %" then "dirty sanchez"
                when m.message_content LIKE "% doggie style %" then "doggie style"
                when m.message_content LIKE "% doggiestyle %" then "doggiestyle"
                when m.message_content LIKE "% doggy style %" then "doggy style"
                when m.message_content LIKE "% doggystyle %" then "doggystyle"
                when m.message_content LIKE "% dog style %" then "dog style"
                when m.message_content LIKE "% dolcett %" then "dolcett"
                when m.message_content LIKE "% domination %" then "domination"
                when m.message_content LIKE "% dominatrix %" then "dominatrix"
                when m.message_content LIKE "% dommes %" then "dommes"
                when m.message_content LIKE "% donkey punch %" then "donkey punch"
                when m.message_content LIKE "% double dong %" then "double dong"
                when m.message_content LIKE "% double penetration %" then "double penetration"
                when m.message_content LIKE "% dp action %" then "dp action"
                when m.message_content LIKE "% dry hump %" then "dry hump"
                when m.message_content LIKE "% dvda %" then "dvda"
                when m.message_content LIKE "% eat my ass %" then "eat my ass"
                when m.message_content LIKE "% ecchi %" then "ecchi"
                when m.message_content LIKE "% ejaculation %" then "ejaculation"
                when m.message_content LIKE "% erotic %" then "erotic"
                when m.message_content LIKE "% erotism %" then "erotism"
                when m.message_content LIKE "% escort %" then "escort"
                when m.message_content LIKE "% eunuch %" then "eunuch"
                when m.message_content LIKE "% fag %" then "fag"
                when m.message_content LIKE "% faggot %" then "faggot"
                when m.message_content LIKE "% fecal %" then "fecal"
                when m.message_content LIKE "% felch %" then "felch"
                when m.message_content LIKE "% fellatio %" then "fellatio"
                when m.message_content LIKE "% feltch %" then "feltch"
                when m.message_content LIKE "% female squirting %" then "female squirting"
                when m.message_content LIKE "% femdom %" then "femdom"
                when m.message_content LIKE "% figging %" then "figging"
                when m.message_content LIKE "% fingerbang %" then "fingerbang"
                when m.message_content LIKE "% fingering %" then "fingering"
                when m.message_content LIKE "% fisting %" then "fisting"
                when m.message_content LIKE "% foot fetish %" then "foot fetish"
                when m.message_content LIKE "% footjob %" then "footjob"
                when m.message_content LIKE "% frotting %" then "frotting"
                when m.message_content LIKE "% fuck %" then "fuck"
                when m.message_content LIKE "% fuck buttons %" then "fuck buttons"
                when m.message_content LIKE "% fuckin %" then "fuckin"
                when m.message_content LIKE "% fucking %" then "fucking"
                when m.message_content LIKE "% fucktards %" then "fucktards"
                when m.message_content LIKE "% fudge packer %" then "fudge packer"
                when m.message_content LIKE "% fudgepacker %" then "fudgepacker"
                when m.message_content LIKE "% futanari %" then "futanari"
                when m.message_content LIKE "% gangbang %" then "gangbang"
                when m.message_content LIKE "% gang bang %" then "gang bang"
                when m.message_content LIKE "% gay sex %" then "gay sex"
                when m.message_content LIKE "% genitals %" then "genitals"
                when m.message_content LIKE "% giant cock %" then "giant cock"
                when m.message_content LIKE "% girl on %" then "girl on"
                when m.message_content LIKE "% girl on top %" then "girl on top"
                when m.message_content LIKE "% girls gone wild %" then "girls gone wild"
                when m.message_content LIKE "% goatcx %" then "goatcx"
                when m.message_content LIKE "% goatse %" then "goatse"
                when m.message_content LIKE "% god damn %" then "god damn"
                when m.message_content LIKE "% gokkun %" then "gokkun"
                when m.message_content LIKE "% golden shower %" then "golden shower"
                when m.message_content LIKE "% goodpoop %" then "goodpoop"
                when m.message_content LIKE "% goo girl %" then "goo girl"
                when m.message_content LIKE "% goregasm %" then "goregasm"
                when m.message_content LIKE "% grope %" then "grope"
                when m.message_content LIKE "% group sex %" then "group sex"
                when m.message_content LIKE "% g-spot %" then "g-spot"
                when m.message_content LIKE "% guro %" then "guro"
                when m.message_content LIKE "% hand job %" then "hand job"
                when m.message_content LIKE "% handjob %" then "handjob"
                when m.message_content LIKE "% hard core %" then "hard core"
                when m.message_content LIKE "% hardcore %" then "hardcore"
                when m.message_content LIKE "% hentai %" then "hentai"
                when m.message_content LIKE "% homoerotic %" then "homoerotic"
                when m.message_content LIKE "% honkey %" then "honkey"
                when m.message_content LIKE "% hooker %" then "hooker"
                when m.message_content LIKE "% horny %" then "horny"
                when m.message_content LIKE "% hot carl %" then "hot carl"
                when m.message_content LIKE "% hot chick %" then "hot chick"
                when m.message_content LIKE "% how to kill %" then "how to kill"
                when m.message_content LIKE "% how to murder %" then "how to murder"
                when m.message_content LIKE "% huge fat %" then "huge fat"
                when m.message_content LIKE "% humping %" then "humping"
                when m.message_content LIKE "% incest %" then "incest"
                when m.message_content LIKE "% intercourse %" then "intercourse"
                when m.message_content LIKE "% jack off %" then "jack off"
                when m.message_content LIKE "% jail bait %" then "jail bait"
                when m.message_content LIKE "% jailbait %" then "jailbait"
                when m.message_content LIKE "% jelly donut %" then "jelly donut"
                when m.message_content LIKE "% jerk off %" then "jerk off"
                when m.message_content LIKE "% jigaboo %" then "jigaboo"
                when m.message_content LIKE "% jiggaboo %" then "jiggaboo"
                when m.message_content LIKE "% jiggerboo %" then "jiggerboo"
                when m.message_content LIKE "% jizz %" then "jizz"
                when m.message_content LIKE "% juggs %" then "juggs"
                when m.message_content LIKE "% kike %" then "kike"
                when m.message_content LIKE "% kinbaku %" then "kinbaku"
                when m.message_content LIKE "% kinkster %" then "kinkster"
                when m.message_content LIKE "% kinky %" then "kinky"
                when m.message_content LIKE "% knobbing %" then "knobbing"
                when m.message_content LIKE "% leather restraint %" then "leather restraint"
                when m.message_content LIKE "% leather straight jacket %" then "leather straight jacket"
                when m.message_content LIKE "% lemon party %" then "lemon party"
                when m.message_content LIKE "% livesex %" then "livesex"
                when m.message_content LIKE "% lolita %" then "lolita"
                when m.message_content LIKE "% lovemaking %" then "lovemaking"
                when m.message_content LIKE "% make me come %" then "make me come"
                when m.message_content LIKE "% male squirting %" then "male squirting"
                when m.message_content LIKE "% masturbate %" then "masturbate"
                when m.message_content LIKE "% masturbating %" then "masturbating"
                when m.message_content LIKE "% masturbation %" then "masturbation"
                when m.message_content LIKE "% menage a trois %" then "menage a trois"
                when m.message_content LIKE "% milf %" then "milf"
                when m.message_content LIKE "% missionary position %" then "missionary position"
                when m.message_content LIKE "% mong %" then "mong"
                when m.message_content LIKE "% motherfucker %" then "motherfucker"
                when m.message_content LIKE "% mound of venus %" then "mound of venus"
                when m.message_content LIKE "% mr hands %" then "mr hands"
                when m.message_content LIKE "% muff diver %" then "muff diver"
                when m.message_content LIKE "% muffdiving %" then "muffdiving"
                when m.message_content LIKE "% nambla %" then "nambla"
                when m.message_content LIKE "% nawashi %" then "nawashi"
                when m.message_content LIKE "% negro %" then "negro"
                when m.message_content LIKE "% neonazi %" then "neonazi"
                when m.message_content LIKE "% nigga %" then "nigga"
                when m.message_content LIKE "% nigger %" then "nigger"
                when m.message_content LIKE "% nig nog %" then "nig nog"
                when m.message_content LIKE "% nimphomania %" then "nimphomania"
                when m.message_content LIKE "% nipple %" then "nipple"
                when m.message_content LIKE "% nipples %" then "nipples"
                when m.message_content LIKE "% nsfw %" then "nsfw"
                when m.message_content LIKE "% nsfw images %" then "nsfw images"
                when m.message_content LIKE "% nude %" then "nude"
                when m.message_content LIKE "% nudity %" then "nudity"
                when m.message_content LIKE "% nutten %" then "nutten"
                when m.message_content LIKE "% nympho %" then "nympho"
                when m.message_content LIKE "% nymphomania %" then "nymphomania"
                when m.message_content LIKE "% octopussy %" then "octopussy"
                when m.message_content LIKE "% omorashi %" then "omorashi"
                when m.message_content LIKE "% one cup two girls %" then "one cup two girls"
                when m.message_content LIKE "% one guy one jar %" then "one guy one jar"
                when m.message_content LIKE "% orgasm %" then "orgasm"
                when m.message_content LIKE "% orgy %" then "orgy"
                when m.message_content LIKE "% paedophile %" then "paedophile"
                when m.message_content LIKE "% paki %" then "paki"
                when m.message_content LIKE "% panties %" then "panties"
                when m.message_content LIKE "% panty %" then "panty"
                when m.message_content LIKE "% pedobear %" then "pedobear"
                when m.message_content LIKE "% pedophile %" then "pedophile"
                when m.message_content LIKE "% pegging %" then "pegging"
                when m.message_content LIKE "% penis %" then "penis"
                when m.message_content LIKE "% phone sex %" then "phone sex"
                when m.message_content LIKE "% piece of shit %" then "piece of shit"
                when m.message_content LIKE "% pikey %" then "pikey"
                when m.message_content LIKE "% pissing %" then "pissing"
                when m.message_content LIKE "% piss pig %" then "piss pig"
                when m.message_content LIKE "% pisspig %" then "pisspig"
                when m.message_content LIKE "% playboy %" then "playboy"
                when m.message_content LIKE "% pleasure chest %" then "pleasure chest"
                when m.message_content LIKE "% pole smoker %" then "pole smoker"
                when m.message_content LIKE "% ponyplay %" then "ponyplay"
                when m.message_content LIKE "% poof %" then "poof"
                when m.message_content LIKE "% poon %" then "poon"
                when m.message_content LIKE "% poontang %" then "poontang"
                when m.message_content LIKE "% punany %" then "punany"
                when m.message_content LIKE "% poop chute %" then "poop chute"
                when m.message_content LIKE "% poopchute %" then "poopchute"
                when m.message_content LIKE "% porn %" then "porn"
                when m.message_content LIKE "% porno %" then "porno"
                when m.message_content LIKE "% pornography %" then "pornography"
                when m.message_content LIKE "% prince albert piercing %" then "prince albert piercing"
                when m.message_content LIKE "% pthc %" then "pthc"
                when m.message_content LIKE "% pubes %" then "pubes"
                when m.message_content LIKE "% pussy %" then "pussy"
                when m.message_content LIKE "% queaf %" then "queaf"
                when m.message_content LIKE "% queef %" then "queef"
                when m.message_content LIKE "% quim %" then "quim"
                when m.message_content LIKE "% raghead %" then "raghead"
                when m.message_content LIKE "% raging boner %" then "raging boner"
                when m.message_content LIKE "% rape %" then "rape"
                when m.message_content LIKE "% raping %" then "raping"
                when m.message_content LIKE "% rapist %" then "rapist"
                when m.message_content LIKE "% rectum %" then "rectum"
                when m.message_content LIKE "% reverse cowgirl %" then "reverse cowgirl"
                when m.message_content LIKE "% rimjob %" then "rimjob"
                when m.message_content LIKE "% rimming %" then "rimming"
                when m.message_content LIKE "% rosy palm %" then "rosy palm"
                when m.message_content LIKE "% rosy palm and her 5 sisters %" then "rosy palm and her 5 sisters"
                when m.message_content LIKE "% rusty trombone %" then "rusty trombone"
                when m.message_content LIKE "% sadism %" then "sadism"
                when m.message_content LIKE "% santorum %" then "santorum"
                when m.message_content LIKE "% scat %" then "scat"
                when m.message_content LIKE "% schlong %" then "schlong"
                when m.message_content LIKE "% scissoring %" then "scissoring"
                when m.message_content LIKE "% semen %" then "semen"
                when m.message_content LIKE "% sex %" then "sex"
                when m.message_content LIKE "% sexcam %" then "sexcam"
                when m.message_content LIKE "% sexo %" then "sexo"
                when m.message_content LIKE "% sexy %" then "sexy"
                when m.message_content LIKE "% sexual %" then "sexual"
                when m.message_content LIKE "% sexually %" then "sexually"
                when m.message_content LIKE "% sexuality %" then "sexuality"
                when m.message_content LIKE "% shaved beaver %" then "shaved beaver"
                when m.message_content LIKE "% shaved pussy %" then "shaved pussy"
                when m.message_content LIKE "% shemale %" then "shemale"
                when m.message_content LIKE "% shibari %" then "shibari"
                when m.message_content LIKE "% shit %" then "shit"
                when m.message_content LIKE "% shitblimp %" then "shitblimp"
                when m.message_content LIKE "% shitty %" then "shitty"
                when m.message_content LIKE "% shota %" then "shota"
                when m.message_content LIKE "% shrimping %" then "shrimping"
                when m.message_content LIKE "% skeet %" then "skeet"
                when m.message_content LIKE "% slanteye %" then "slanteye"
                when m.message_content LIKE "% slut %" then "slut"
                when m.message_content LIKE "% s&m %" then "s&m"
                when m.message_content LIKE "% smut %" then "smut"
                when m.message_content LIKE "% snatch %" then "snatch"
                when m.message_content LIKE "% snowballing %" then "snowballing"
                when m.message_content LIKE "% sodomize %" then "sodomize"
                when m.message_content LIKE "% sodomy %" then "sodomy"
                when m.message_content LIKE "% spastic %" then "spastic"
                when m.message_content LIKE "% spic %" then "spic"
                when m.message_content LIKE "% splooge %" then "splooge"
                when m.message_content LIKE "% splooge moose %" then "splooge moose"
                when m.message_content LIKE "% spooge %" then "spooge"
                when m.message_content LIKE "% spread legs %" then "spread legs"
                when m.message_content LIKE "% spunk %" then "spunk"
                when m.message_content LIKE "% strap on %" then "strap on"
                when m.message_content LIKE "% strapon %" then "strapon"
                when m.message_content LIKE "% strappado %" then "strappado"
                when m.message_content LIKE "% strip club %" then "strip club"
                when m.message_content LIKE "% style doggy %" then "style doggy"
                when m.message_content LIKE "% suck %" then "suck"
                when m.message_content LIKE "% sucks %" then "sucks"
                when m.message_content LIKE "% suicide girls %" then "suicide girls"
                when m.message_content LIKE "% sultry women %" then "sultry women"
                when m.message_content LIKE "% swastika %" then "swastika"
                when m.message_content LIKE "% swinger %" then "swinger"
                when m.message_content LIKE "% tainted love %" then "tainted love"
                when m.message_content LIKE "% taste my %" then "taste my"
                when m.message_content LIKE "% tea bagging %" then "tea bagging"
                when m.message_content LIKE "% threesome %" then "threesome"
                when m.message_content LIKE "% throating %" then "throating"
                when m.message_content LIKE "% thumbzilla %" then "thumbzilla"
                when m.message_content LIKE "% tied up %" then "tied up"
                when m.message_content LIKE "% tight white %" then "tight white"
                when m.message_content LIKE "% tit %" then "tit"
                when m.message_content LIKE "% tits %" then "tits"
                when m.message_content LIKE "% titties %" then "titties"
                when m.message_content LIKE "% titty %" then "titty"
                when m.message_content LIKE "% tongue in a %" then "tongue in a"
                when m.message_content LIKE "% topless %" then "topless"
                when m.message_content LIKE "% tosser %" then "tosser"
                when m.message_content LIKE "% towelhead %" then "towelhead"
                when m.message_content LIKE "% tranny %" then "tranny"
                when m.message_content LIKE "% tribadism %" then "tribadism"
                when m.message_content LIKE "% tub girl %" then "tub girl"
                when m.message_content LIKE "% tubgirl %" then "tubgirl"
                when m.message_content LIKE "% tushy %" then "tushy"
                when m.message_content LIKE "% twat %" then "twat"
                when m.message_content LIKE "% twink %" then "twink"
                when m.message_content LIKE "% twinkie %" then "twinkie"
                when m.message_content LIKE "% two girls one cup %" then "two girls one cup"
                when m.message_content LIKE "% undressing %" then "undressing"
                when m.message_content LIKE "% upskirt %" then "upskirt"
                when m.message_content LIKE "% urethra play %" then "urethra play"
                when m.message_content LIKE "% urophilia %" then "urophilia"
                when m.message_content LIKE "% vagina %" then "vagina"
                when m.message_content LIKE "% venus mound %" then "venus mound"
                when m.message_content LIKE "% viagra %" then "viagra"
                when m.message_content LIKE "% vibrator %" then "vibrator"
                when m.message_content LIKE "% violet wand %" then "violet wand"
                when m.message_content LIKE "% vorarephilia %" then "vorarephilia"
                when m.message_content LIKE "% voyeur %" then "voyeur"
                when m.message_content LIKE "% voyeurweb %" then "voyeurweb"
                when m.message_content LIKE "% voyuer %" then "voyuer"
                when m.message_content LIKE "% vulva %" then "vulva"
                when m.message_content LIKE "% wank %" then "wank"
                when m.message_content LIKE "% wetback %" then "wetback"
                when m.message_content LIKE "% wet dream %" then "wet dream"
                when m.message_content LIKE "% white power %" then "white power"
                when m.message_content LIKE "% whore %" then "whore"
                when m.message_content LIKE "% worldsex %" then "worldsex"
                when m.message_content LIKE "% wrapping men %" then "wrapping men"
                when m.message_content LIKE "% wrinkled starfish %" then "wrinkled starfish"
                when m.message_content LIKE "% xx %" then "xx"
                when m.message_content LIKE "% xxx %" then "xxx"
                when m.message_content LIKE "% yaoi %" then "yaoi"
                when m.message_content LIKE "% yellow showers %" then "yellow showers"
                when m.message_content LIKE "% yiffy %" then "yiffy"
                when m.message_content LIKE "% zoophilia %" then "zoophilia"
                when m.message_content LIKE "% 🖕 %" then "🖕"
                when m.message_content LIKE "% kitty %" then "kitty"
                when m.message_content LIKE "% nyour nut syre %" then "nyour nut syre"
                when m.message_content LIKE "% would be wet in one second %" then "would be wet in one second"
                when m.message_content LIKE "% wet and throbbing %" then "wet and throbbing"
                when m.message_content LIKE "% pulsating %" then "pulsating"
                when m.message_content LIKE "% spasm %" then "spasm"
                when m.message_content LIKE "% get excited %" then "get excited"
                when m.message_content LIKE "% tubercle %" then "tubercle"
                when m.message_content LIKE "% scream %" then "scream"
                when m.message_content LIKE "% vulnerable place %" then "vulnerable place"
                when m.message_content LIKE "% fetishe %" then "fetishe"
                when m.message_content LIKE "% bisexual %" then "bisexual"
                when m.message_content LIKE "% wet %" then "wet"
                when m.message_content LIKE "% Did you get laid %" then "Did you get laid"
                when m.message_content LIKE "% pu. Y %" then "pu. Y"
                when m.message_content LIKE "% stroke %" then "stroke"
                when m.message_content LIKE "% I would like to communicate with you on some frank topics in letters, it should remain there) My love %" then "I would like to communicate with you on some frank topics in letters, it should remain there) My love"
                when m.message_content LIKE "% touch me %" then "touch me"
                when m.message_content LIKE "% Can I tell you what my fingers did last night thinking about you? %" then "Can I tell you what my fingers did last night thinking about you?"
                when m.message_content LIKE "% hose %" then "hose"
                when m.message_content LIKE "% indecent thought %" then "indecent thought"
                when m.message_content LIKE "% passion %" then "passion"
                when m.message_content LIKE "% most sensitive place %" then "most sensitive place"
                when m.message_content LIKE "% jugg %" then "jugg"
                when m.message_content LIKE "% make love %" then "make love"
                when m.message_content LIKE "% fuckbuddy %" then "fuckbuddy"
                when m.message_content LIKE "% swallowing %" then "swallowing"
                when m.message_content LIKE "% Fuck me %" then "Fuck me"
                when m.message_content LIKE "% chocolate eye %" then "chocolate eye"
                when m.message_content LIKE "% spread my legs %" then "spread my legs"
                when m.message_content LIKE "% take it off %" then "take it off"
                when m.message_content LIKE "% in bed %" then "in bed"
                when m.message_content LIKE "% caress %" then "caress"
                when m.message_content LIKE "% every part of your body %" then "every part of your body"
                when m.message_content LIKE "% sit on your face %" then "sit on your face"
                when m.message_content LIKE "% hose your down %" then "hose your down"
                when m.message_content LIKE "% vigra %" then "vigra"
                when m.message_content LIKE "% stimulat %" then "stimulat"
                ELSE NULL
            END AS `word`
        FROM chat_message m
            LEFT JOIN operators uo ON m.operator_id = uo.id -- LEFT JOIN operators u ON uo.agency_id=u.id
        WHERE m.date_created_kiev = date(NOW()) - INTERVAL 1 day
            AND m.message_type = "SENT_TEXT"
            AND (
                m.message_content LIKE "% moan %"
                OR m.message_content LIKE "% take it in my mouth %"
                OR m.message_content LIKE "% breaks and nipples %"
                OR m.message_content LIKE "% suck me dry %"
                OR m.message_content LIKE "% sucking licking %"
                OR m.message_content LIKE "% to kiss the sweetest places on my body %"
                OR m.message_content LIKE "% CYKA %"
                OR m.message_content LIKE "% intimate %"
                OR m.message_content LIKE "% groin %"
                OR m.message_content LIKE "% masturbator %"
                OR m.message_content LIKE "% arouse %"
                OR m.message_content LIKE "% dogs out %"
                OR m.message_content LIKE "% squirt %"
                OR m.message_content LIKE "% oral %"
                OR m.message_content LIKE "% erect breasts %"
                OR m.message_content LIKE "% curvy bottom %"
                OR m.message_content LIKE "% fuk off %"
                OR m.message_content LIKE "% deepthroating %"
                OR m.message_content LIKE "% lusty chat %"
                OR m.message_content LIKE "% naughty pic %"
                OR m.message_content LIKE "% lace lingerie set %"
                OR m.message_content LIKE "% without clothe %"
                OR m.message_content LIKE "% main organ %"
                OR m.message_content LIKE "% collection of gadgets for single ladies %"
                OR m.message_content LIKE "% hottass %"
                OR m.message_content LIKE "% striptease %"
                OR m.message_content LIKE "% dominate %"
                OR m.message_content LIKE "% lick %"
                OR m.message_content LIKE "% legs are spread %"
                OR m.message_content LIKE "% without pant %"
                OR m.message_content LIKE "% turn you on %"
                OR m.message_content LIKE "% squeeze %"
                OR m.message_content LIKE "% vozbuzhdayesh %"
                OR m.message_content LIKE "% crotch up %"
                OR m.message_content LIKE "% genital %"
                OR m.message_content LIKE "% kum %"
                OR m.message_content LIKE "% wit woo %"
                OR m.message_content LIKE "% naked %"
                OR m.message_content LIKE "% puss  %"
                OR m.message_content LIKE "% You can sit on my face %"
                OR m.message_content LIKE "% fuck with me %"
                OR m.message_content LIKE "% teats %"
                OR m.message_content LIKE "% i wanna eat you %"
                OR m.message_content LIKE "% please send me pic %"
                OR m.message_content LIKE "% dic-photo %"
                OR m.message_content LIKE "% dic pic %"
                OR m.message_content LIKE "% sexting %"
                OR m.message_content LIKE "% throbbing %"
                OR m.message_content LIKE "% licker %"
                OR m.message_content LIKE "% cocksucker %"
                OR m.message_content LIKE "% still keeping it straight %"
                OR m.message_content LIKE "% dirty chat %"
                OR m.message_content LIKE "% sexie %"
                OR m.message_content LIKE "% intens and nakke %"
                OR m.message_content LIKE "% come off %"
                OR m.message_content LIKE "% saliva %"
                OR m.message_content LIKE "% lube %"
                OR m.message_content LIKE "% coochie %"
                OR m.message_content LIKE "% cowgirl %"
                OR m.message_content LIKE "% doggy %"
                OR m.message_content LIKE "% no clothing %"
                OR m.message_content LIKE "% eating pussy %"
                OR m.message_content LIKE "% mistress %"
                OR m.message_content LIKE "% bare %"
                OR m.message_content LIKE "% underwear %"
                OR m.message_content LIKE "% hot night %"
                OR m.message_content LIKE "% breasts %"
                OR m.message_content LIKE "% hot lover %"
                OR m.message_content LIKE "% conjugal duty %"
                OR m.message_content LIKE "% throb %"
                OR m.message_content LIKE "% spank %"
                OR m.message_content LIKE "% setting on my face %"
                OR m.message_content LIKE "% lingerie %"
                OR m.message_content LIKE "% sex pod %"
                OR m.message_content LIKE "% ecstasy %"
                OR m.message_content LIKE "% condom %"
                OR m.message_content LIKE "% Contex %"
                OR m.message_content LIKE "% Durex %"
                OR m.message_content LIKE "% nightie %"
                OR m.message_content LIKE "% betweenness %"
                OR m.message_content LIKE "% tie my hands %"
                OR m.message_content LIKE "% kamasutra %"
                OR m.message_content LIKE "% caresses %"
                OR m.message_content LIKE "% bra %"
                OR m.message_content LIKE "% hose you down %"
                OR m.message_content LIKE "% 2g1c %"
                OR m.message_content LIKE "% 2 girls 1 cup %"
                OR m.message_content LIKE "% acrotomophilia %"
                OR m.message_content LIKE "% alabama hot pocket %"
                OR m.message_content LIKE "% alaskan pipeline %"
                OR m.message_content LIKE "% anal %"
                OR m.message_content LIKE "% anilingus %"
                OR m.message_content LIKE "% anus %"
                OR m.message_content LIKE "% apeshit %"
                OR m.message_content LIKE "% arsehole %"
                OR m.message_content LIKE "% ass %"
                OR m.message_content LIKE "% asshole %"
                OR m.message_content LIKE "% assmunch %"
                OR m.message_content LIKE "% auto erotic %"
                OR m.message_content LIKE "% autoerotic %"
                OR m.message_content LIKE "% babeland %"
                OR m.message_content LIKE "% baby batter %"
                OR m.message_content LIKE "% baby juice %"
                OR m.message_content LIKE "% ball gag %"
                OR m.message_content LIKE "% ball gravy %"
                OR m.message_content LIKE "% ball kicking %"
                OR m.message_content LIKE "% ball licking %"
                OR m.message_content LIKE "% ball sack %"
                OR m.message_content LIKE "% ball sucking %"
                OR m.message_content LIKE "% bangbros %"
                OR m.message_content LIKE "% bangbus %"
                OR m.message_content LIKE "% bareback %"
                OR m.message_content LIKE "% barely legal %"
                OR m.message_content LIKE "% barenaked %"
                OR m.message_content LIKE "% bastard %"
                OR m.message_content LIKE "% bastardo %"
                OR m.message_content LIKE "% bastinado %"
                OR m.message_content LIKE "% bbw %"
                OR m.message_content LIKE "% bdsm %"
                OR m.message_content LIKE "% beaner %"
                OR m.message_content LIKE "% beaners %"
                OR m.message_content LIKE "% beaver cleaver %"
                OR m.message_content LIKE "% beaver lips %"
                OR m.message_content LIKE "% beastiality %"
                OR m.message_content LIKE "% bestiality %"
                OR m.message_content LIKE "% big black %"
                OR m.message_content LIKE "% big breasts %"
                OR m.message_content LIKE "% big knockers %"
                OR m.message_content LIKE "% big tits %"
                OR m.message_content LIKE "% bimbos %"
                OR m.message_content LIKE "% birdlock %"
                OR m.message_content LIKE "% bitch %"
                OR m.message_content LIKE "% bitches %"
                OR m.message_content LIKE "% black cock %"
                OR m.message_content LIKE "% blonde action %"
                OR m.message_content LIKE "% blonde on blonde action %"
                OR m.message_content LIKE "% blowjob %"
                OR m.message_content LIKE "% blow job %"
                OR m.message_content LIKE "% blow your load %"
                OR m.message_content LIKE "% blue waffle %"
                OR m.message_content LIKE "% blumpkin %"
                OR m.message_content LIKE "% bollocks %"
                OR m.message_content LIKE "% bondage %"
                OR m.message_content LIKE "% boner %"
                OR m.message_content LIKE "% boob %"
                OR m.message_content LIKE "% boobs %"
                OR m.message_content LIKE "% booty call %"
                OR m.message_content LIKE "% brown showers %"
                OR m.message_content LIKE "% brunette action %"
                OR m.message_content LIKE "% bukkake %"
                OR m.message_content LIKE "% bulldyke %"
                OR m.message_content LIKE "% bullet vibe %"
                OR m.message_content LIKE "% bullshit %"
                OR m.message_content LIKE "% bung hole %"
                OR m.message_content LIKE "% bunghole %"
                OR m.message_content LIKE "% busty %"
                OR m.message_content LIKE "% butt %"
                OR m.message_content LIKE "% buttcheeks %"
                OR m.message_content LIKE "% butthole %"
                OR m.message_content LIKE "% camel toe %"
                OR m.message_content LIKE "% camgirl %"
                OR m.message_content LIKE "% camslut %"
                OR m.message_content LIKE "% camwhore %"
                OR m.message_content LIKE "% carpet muncher %"
                OR m.message_content LIKE "% carpetmuncher %"
                OR m.message_content LIKE "% chocolate rosebuds %"
                OR m.message_content LIKE "% cialis %"
                OR m.message_content LIKE "% circlejerk %"
                OR m.message_content LIKE "% cleveland steamer %"
                OR m.message_content LIKE "% clit %"
                OR m.message_content LIKE "% clitoris %"
                OR m.message_content LIKE "% clover clamps %"
                OR m.message_content LIKE "% clusterfuck %"
                OR m.message_content LIKE "% cock %"
                OR m.message_content LIKE "% cocks %"
                OR m.message_content LIKE "% coprolagnia %"
                OR m.message_content LIKE "% coprophilia %"
                OR m.message_content LIKE "% cornhole %"
                OR m.message_content LIKE "% coon %"
                OR m.message_content LIKE "% coons %"
                OR m.message_content LIKE "% creampie %"
                OR m.message_content LIKE "% cum %"
                OR m.message_content LIKE "% cumming %"
                OR m.message_content LIKE "% cumshot %"
                OR m.message_content LIKE "% cumshots %"
                OR m.message_content LIKE "% cunnilingus %"
                OR m.message_content LIKE "% cunt %"
                OR m.message_content LIKE "% darkie %"
                OR m.message_content LIKE "% date rape %"
                OR m.message_content LIKE "% daterape %"
                OR m.message_content LIKE "% deep throat %"
                OR m.message_content LIKE "% deepthroat %"
                OR m.message_content LIKE "% dendrophilia %"
                OR m.message_content LIKE "% dick %"
                OR m.message_content LIKE "% dildo %"
                OR m.message_content LIKE "% dingleberry %"
                OR m.message_content LIKE "% dingleberries %"
                OR m.message_content LIKE "% dirty pillows %"
                OR m.message_content LIKE "% dirty sanchez %"
                OR m.message_content LIKE "% doggie style %"
                OR m.message_content LIKE "% doggiestyle %"
                OR m.message_content LIKE "% doggy style %"
                OR m.message_content LIKE "% doggystyle %"
                OR m.message_content LIKE "% dog style %"
                OR m.message_content LIKE "% dolcett %"
                OR m.message_content LIKE "% domination %"
                OR m.message_content LIKE "% dominatrix %"
                OR m.message_content LIKE "% dommes %"
                OR m.message_content LIKE "% donkey punch %"
                OR m.message_content LIKE "% double dong %"
                OR m.message_content LIKE "% double penetration %"
                OR m.message_content LIKE "% dp action %"
                OR m.message_content LIKE "% dry hump %"
                OR m.message_content LIKE "% dvda %"
                OR m.message_content LIKE "% eat my ass %"
                OR m.message_content LIKE "% ecchi %"
                OR m.message_content LIKE "% ejaculation %"
                OR m.message_content LIKE "% erotic %"
                OR m.message_content LIKE "% erotism %"
                OR m.message_content LIKE "% escort %"
                OR m.message_content LIKE "% eunuch %"
                OR m.message_content LIKE "% fag %"
                OR m.message_content LIKE "% faggot %"
                OR m.message_content LIKE "% fecal %"
                OR m.message_content LIKE "% felch %"
                OR m.message_content LIKE "% fellatio %"
                OR m.message_content LIKE "% feltch %"
                OR m.message_content LIKE "% female squirting %"
                OR m.message_content LIKE "% femdom %"
                OR m.message_content LIKE "% figging %"
                OR m.message_content LIKE "% fingerbang %"
                OR m.message_content LIKE "% fingering %"
                OR m.message_content LIKE "% fisting %"
                OR m.message_content LIKE "% foot fetish %"
                OR m.message_content LIKE "% footjob %"
                OR m.message_content LIKE "% frotting %"
                OR m.message_content LIKE "% fuck %"
                OR m.message_content LIKE "% fuck buttons %"
                OR m.message_content LIKE "% fuckin %"
                OR m.message_content LIKE "% fucking %"
                OR m.message_content LIKE "% fucktards %"
                OR m.message_content LIKE "% fudge packer %"
                OR m.message_content LIKE "% fudgepacker %"
                OR m.message_content LIKE "% futanari %"
                OR m.message_content LIKE "% gangbang %"
                OR m.message_content LIKE "% gang bang %"
                OR m.message_content LIKE "% gay sex %"
                OR m.message_content LIKE "% genitals %"
                OR m.message_content LIKE "% giant cock %"
                OR m.message_content LIKE "% girl on %"
                OR m.message_content LIKE "% girl on top %"
                OR m.message_content LIKE "% girls gone wild %"
                OR m.message_content LIKE "% goatcx %"
                OR m.message_content LIKE "% goatse %"
                OR m.message_content LIKE "% god damn %"
                OR m.message_content LIKE "% gokkun %"
                OR m.message_content LIKE "% golden shower %"
                OR m.message_content LIKE "% goodpoop %"
                OR m.message_content LIKE "% goo girl %"
                OR m.message_content LIKE "% goregasm %"
                OR m.message_content LIKE "% grope %"
                OR m.message_content LIKE "% group sex %"
                OR m.message_content LIKE "% g-spot %"
                OR m.message_content LIKE "% guro %"
                OR m.message_content LIKE "% hand job %"
                OR m.message_content LIKE "% handjob %"
                OR m.message_content LIKE "% hard core %"
                OR m.message_content LIKE "% hardcore %"
                OR m.message_content LIKE "% hentai %"
                OR m.message_content LIKE "% homoerotic %"
                OR m.message_content LIKE "% honkey %"
                OR m.message_content LIKE "% hooker %"
                OR m.message_content LIKE "% horny %"
                OR m.message_content LIKE "% hot carl %"
                OR m.message_content LIKE "% hot chick %"
                OR m.message_content LIKE "% how to kill %"
                OR m.message_content LIKE "% how to murder %"
                OR m.message_content LIKE "% huge fat %"
                OR m.message_content LIKE "% humping %"
                OR m.message_content LIKE "% incest %"
                OR m.message_content LIKE "% intercourse %"
                OR m.message_content LIKE "% jack off %"
                OR m.message_content LIKE "% jail bait %"
                OR m.message_content LIKE "% jailbait %"
                OR m.message_content LIKE "% jelly donut %"
                OR m.message_content LIKE "% jerk off %"
                OR m.message_content LIKE "% jigaboo %"
                OR m.message_content LIKE "% jiggaboo %"
                OR m.message_content LIKE "% jiggerboo %"
                OR m.message_content LIKE "% jizz %"
                OR m.message_content LIKE "% juggs %"
                OR m.message_content LIKE "% kike %"
                OR m.message_content LIKE "% kinbaku %"
                OR m.message_content LIKE "% kinkster %"
                OR m.message_content LIKE "% kinky %"
                OR m.message_content LIKE "% knobbing %"
                OR m.message_content LIKE "% leather restraint %"
                OR m.message_content LIKE "% leather straight jacket %"
                OR m.message_content LIKE "% lemon party %"
                OR m.message_content LIKE "% livesex %"
                OR m.message_content LIKE "% lolita %"
                OR m.message_content LIKE "% lovemaking %"
                OR m.message_content LIKE "% make me come %"
                OR m.message_content LIKE "% male squirting %"
                OR m.message_content LIKE "% masturbate %"
                OR m.message_content LIKE "% masturbating %"
                OR m.message_content LIKE "% masturbation %"
                OR m.message_content LIKE "% menage a trois %"
                OR m.message_content LIKE "% milf %"
                OR m.message_content LIKE "% missionary position %"
                OR m.message_content LIKE "% mong %"
                OR m.message_content LIKE "% motherfucker %"
                OR m.message_content LIKE "% mound of venus %"
                OR m.message_content LIKE "% mr hands %"
                OR m.message_content LIKE "% muff diver %"
                OR m.message_content LIKE "% muffdiving %"
                OR m.message_content LIKE "% nambla %"
                OR m.message_content LIKE "% nawashi %"
                OR m.message_content LIKE "% negro %"
                OR m.message_content LIKE "% neonazi %"
                OR m.message_content LIKE "% nigga %"
                OR m.message_content LIKE "% nigger %"
                OR m.message_content LIKE "% nig nog %"
                OR m.message_content LIKE "% nimphomania %"
                OR m.message_content LIKE "% nipple %"
                OR m.message_content LIKE "% nipples %"
                OR m.message_content LIKE "% nsfw %"
                OR m.message_content LIKE "% nsfw images %"
                OR m.message_content LIKE "% nude %"
                OR m.message_content LIKE "% nudity %"
                OR m.message_content LIKE "% nutten %"
                OR m.message_content LIKE "% nympho %"
                OR m.message_content LIKE "% nymphomania %"
                OR m.message_content LIKE "% octopussy %"
                OR m.message_content LIKE "% omorashi %"
                OR m.message_content LIKE "% one cup two girls %"
                OR m.message_content LIKE "% one guy one jar %"
                OR m.message_content LIKE "% orgasm %"
                OR m.message_content LIKE "% orgy %"
                OR m.message_content LIKE "% paedophile %"
                OR m.message_content LIKE "% paki %"
                OR m.message_content LIKE "% panties %"
                OR m.message_content LIKE "% panty %"
                OR m.message_content LIKE "% pedobear %"
                OR m.message_content LIKE "% pedophile %"
                OR m.message_content LIKE "% pegging %"
                OR m.message_content LIKE "% penis %"
                OR m.message_content LIKE "% phone sex %"
                OR m.message_content LIKE "% piece of shit %"
                OR m.message_content LIKE "% pikey %"
                OR m.message_content LIKE "% pissing %"
                OR m.message_content LIKE "% piss pig %"
                OR m.message_content LIKE "% pisspig %"
                OR m.message_content LIKE "% playboy %"
                OR m.message_content LIKE "% pleasure chest %"
                OR m.message_content LIKE "% pole smoker %"
                OR m.message_content LIKE "% ponyplay %"
                OR m.message_content LIKE "% poof %"
                OR m.message_content LIKE "% poon %"
                OR m.message_content LIKE "% poontang %"
                OR m.message_content LIKE "% punany %"
                OR m.message_content LIKE "% poop chute %"
                OR m.message_content LIKE "% poopchute %"
                OR m.message_content LIKE "% porn %"
                OR m.message_content LIKE "% porno %"
                OR m.message_content LIKE "% pornography %"
                OR m.message_content LIKE "% prince albert piercing %"
                OR m.message_content LIKE "% pthc %"
                OR m.message_content LIKE "% pubes %"
                OR m.message_content LIKE "% pussy %"
                OR m.message_content LIKE "% queaf %"
                OR m.message_content LIKE "% queef %"
                OR m.message_content LIKE "% quim %"
                OR m.message_content LIKE "% raghead %"
                OR m.message_content LIKE "% raging boner %"
                OR m.message_content LIKE "% rape %"
                OR m.message_content LIKE "% raping %"
                OR m.message_content LIKE "% rapist %"
                OR m.message_content LIKE "% rectum %"
                OR m.message_content LIKE "% reverse cowgirl %"
                OR m.message_content LIKE "% rimjob %"
                OR m.message_content LIKE "% rimming %"
                OR m.message_content LIKE "% rosy palm %"
                OR m.message_content LIKE "% rosy palm and her 5 sisters %"
                OR m.message_content LIKE "% rusty trombone %"
                OR m.message_content LIKE "% sadism %"
                OR m.message_content LIKE "% santorum %"
                OR m.message_content LIKE "% scat %"
                OR m.message_content LIKE "% schlong %"
                OR m.message_content LIKE "% scissoring %"
                OR m.message_content LIKE "% semen %"
                OR m.message_content LIKE "% sex %"
                OR m.message_content LIKE "% sexcam %"
                OR m.message_content LIKE "% sexo %"
                OR m.message_content LIKE "% sexy %"
                OR m.message_content LIKE "% sexual %"
                OR m.message_content LIKE "% sexually %"
                OR m.message_content LIKE "% sexuality %"
                OR m.message_content LIKE "% shaved beaver %"
                OR m.message_content LIKE "% shaved pussy %"
                OR m.message_content LIKE "% shemale %"
                OR m.message_content LIKE "% shibari %"
                OR m.message_content LIKE "% shit %"
                OR m.message_content LIKE "% shitblimp %"
                OR m.message_content LIKE "% shitty %"
                OR m.message_content LIKE "% shota %"
                OR m.message_content LIKE "% shrimping %"
                OR m.message_content LIKE "% skeet %"
                OR m.message_content LIKE "% slanteye %"
                OR m.message_content LIKE "% slut %"
                OR m.message_content LIKE "% s&m %"
                OR m.message_content LIKE "% smut %"
                OR m.message_content LIKE "% snatch %"
                OR m.message_content LIKE "% snowballing %"
                OR m.message_content LIKE "% sodomize %"
                OR m.message_content LIKE "% sodomy %"
                OR m.message_content LIKE "% spastic %"
                OR m.message_content LIKE "% spic %"
                OR m.message_content LIKE "% splooge %"
                OR m.message_content LIKE "% splooge moose %"
                OR m.message_content LIKE "% spooge %"
                OR m.message_content LIKE "% spread legs %"
                OR m.message_content LIKE "% spunk %"
                OR m.message_content LIKE "% strap on %"
                OR m.message_content LIKE "% strapon %"
                OR m.message_content LIKE "% strappado %"
                OR m.message_content LIKE "% strip club %"
                OR m.message_content LIKE "% style doggy %"
                OR m.message_content LIKE "% suck %"
                OR m.message_content LIKE "% sucks %"
                OR m.message_content LIKE "% suicide girls %"
                OR m.message_content LIKE "% sultry women %"
                OR m.message_content LIKE "% swastika %"
                OR m.message_content LIKE "% swinger %"
                OR m.message_content LIKE "% tainted love %"
                OR m.message_content LIKE "% taste my %"
                OR m.message_content LIKE "% tea bagging %"
                OR m.message_content LIKE "% threesome %"
                OR m.message_content LIKE "% throating %"
                OR m.message_content LIKE "% thumbzilla %"
                OR m.message_content LIKE "% tied up %"
                OR m.message_content LIKE "% tight white %"
                OR m.message_content LIKE "% tit %"
                OR m.message_content LIKE "% tits %"
                OR m.message_content LIKE "% titties %"
                OR m.message_content LIKE "% titty %"
                OR m.message_content LIKE "% tongue in a %"
                OR m.message_content LIKE "% topless %"
                OR m.message_content LIKE "% tosser %"
                OR m.message_content LIKE "% towelhead %"
                OR m.message_content LIKE "% tranny %"
                OR m.message_content LIKE "% tribadism %"
                OR m.message_content LIKE "% tub girl %"
                OR m.message_content LIKE "% tubgirl %"
                OR m.message_content LIKE "% tushy %"
                OR m.message_content LIKE "% twat %"
                OR m.message_content LIKE "% twink %"
                OR m.message_content LIKE "% twinkie %"
                OR m.message_content LIKE "% two girls one cup %"
                OR m.message_content LIKE "% undressing %"
                OR m.message_content LIKE "% upskirt %"
                OR m.message_content LIKE "% urethra play %"
                OR m.message_content LIKE "% urophilia %"
                OR m.message_content LIKE "% vagina %"
                OR m.message_content LIKE "% venus mound %"
                OR m.message_content LIKE "% viagra %"
                OR m.message_content LIKE "% vibrator %"
                OR m.message_content LIKE "% violet wand %"
                OR m.message_content LIKE "% vorarephilia %"
                OR m.message_content LIKE "% voyeur %"
                OR m.message_content LIKE "% voyeurweb %"
                OR m.message_content LIKE "% voyuer %"
                OR m.message_content LIKE "% vulva %"
                OR m.message_content LIKE "% wank %"
                OR m.message_content LIKE "% wetback %"
                OR m.message_content LIKE "% wet dream %"
                OR m.message_content LIKE "% white power %"
                OR m.message_content LIKE "% whore %"
                OR m.message_content LIKE "% worldsex %"
                OR m.message_content LIKE "% wrapping men %"
                OR m.message_content LIKE "% wrinkled starfish %"
                OR m.message_content LIKE "% xx %"
                OR m.message_content LIKE "% xxx %"
                OR m.message_content LIKE "% yaoi %"
                OR m.message_content LIKE "% yellow showers %"
                OR m.message_content LIKE "% yiffy %"
                OR m.message_content LIKE "% zoophilia %"
                OR m.message_content LIKE "% 🖕 %"
                OR m.message_content LIKE "% kitty %"
                OR m.message_content LIKE "% nyour nut syre %"
                OR m.message_content LIKE "% would be wet in one second %"
                OR m.message_content LIKE "% wet and throbbing %"
                OR m.message_content LIKE "% pulsating %"
                OR m.message_content LIKE "% spasm %"
                OR m.message_content LIKE "% get excited %"
                OR m.message_content LIKE "% tubercle %"
                OR m.message_content LIKE "% scream %"
                OR m.message_content LIKE "% vulnerable place %"
                OR m.message_content LIKE "% fetishe %"
                OR m.message_content LIKE "% bisexual %"
                OR m.message_content LIKE "% wet %"
                OR m.message_content LIKE "% Did you get laid %"
                OR m.message_content LIKE "% pu. Y %"
                OR m.message_content LIKE "% stroke %"
                OR m.message_content LIKE "% I would like to communicate with you on some frank topics in letters, it should remain there) My love %"
                OR m.message_content LIKE "% touch me %"
                OR m.message_content LIKE "% Can I tell you what my fingers did last night thinking about you? %"
                OR m.message_content LIKE "% hose %"
                OR m.message_content LIKE "% indecent thought %"
                OR m.message_content LIKE "% passion %"
                OR m.message_content LIKE "% most sensitive place %"
                OR m.message_content LIKE "% jugg %"
                OR m.message_content LIKE "% make love %"
                OR m.message_content LIKE "% fuckbuddy %"
                OR m.message_content LIKE "% swallowing %"
                OR m.message_content LIKE "% Fuck me %"
                OR m.message_content LIKE "% chocolate eye %"
                OR m.message_content LIKE "% spread my legs %"
                OR m.message_content LIKE "% take it off %"
                OR m.message_content LIKE "% in bed %"
                OR m.message_content LIKE "% caress %"
                OR m.message_content LIKE "% every part of your body %"
                OR m.message_content LIKE "% sit on your face %"
                OR m.message_content LIKE "% hose your down %"
                OR m.message_content LIKE "% vigra %"
                OR m.message_content LIKE "% stimulat %"
            )
    ) tt
    left JOIN profiles up ON tt.`man_id` = up.id